{
 "title": "/System-Details",
 "description": "Show system level metrics on a host",
 "tags": [
  "detail",
  "system"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "label_values(host)" },
   { "name": "rate_interval", "query": "2m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{host=~\"$host\",cpu=\"cpu-total\"} + cpu_usage_guest{host=~\"$host\",cpu=\"cpu-total\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_total{host=~\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mem_used{host=~\"$host\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk: Free Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_total{host=~\"$host\",device!~\"overlay|tmpfs|devtmpfs\"} - disk_used{host=~\"$host\",device!~\"overlay|tmpfs|devtmpfs\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk: Free Inodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "disk_inodes_free{host=~\"$host\",device!~\"overlay|devtmpfs|tmpfs\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network: Recv Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=~\"$host\"}[$rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Network: Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_sent{host=~\"$host\"}[$rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}